### ISSUE TITLE
Provide option to leave repository clean

### ISSUE THREAD

**Issue by filipkowicz** [einaregilsson/build-number#7]
current plugin saves build number to `BUILD_NUMBER/BUILD_NUMBER` file. I would like to have it clean and pass between jobs with artefacts (it might be better option as default as well)

please add option for that

current workaround - add `BUILD_NUMBER` to git ignore

**Comment by einaregilsson** [comment]
We already use upload-artefact and download-artefact to pass the data, but those work on files, which is why we have the BUILD_NUMBER file. 

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow

Unless there's a newer way I'm not aware of? You could always add a one line
`- runs: rm BUILD_NUMBER/BUILD_NUMBER` command after the build number has been retrieved.

**Comment by filipkowicz** [comment]
yeah removing is also good option, closing then

Removing by default could be good option too
